// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7jQDPmA7koyRgiNNHA4zYRIx7T8wnEz0',
    appId: '1:1098012852802:web:4074c5b57549cd14d023db',
    messagingSenderId: '1098012852802',
    projectId: 'green-house-monitoring-4f6c7',
    authDomain: 'green-house-monitoring-4f6c7.firebaseapp.com',
    storageBucket: 'green-house-monitoring-4f6c7.appspot.com',
    measurementId: 'G-Q4XGRM2GVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMf_3QMVYAdNPYQsV9e-vJDr2VrGjYyZU',
    appId: '1:1098012852802:android:5700614bcb1b412cd023db',
    messagingSenderId: '1098012852802',
    projectId: 'green-house-monitoring-4f6c7',
    storageBucket: 'green-house-monitoring-4f6c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkiFyBP42CMk9DFLFZZ5QlRwa9ETqoJPs',
    appId: '1:1098012852802:ios:5e6dbd866e7ba9b4d023db',
    messagingSenderId: '1098012852802',
    projectId: 'green-house-monitoring-4f6c7',
    storageBucket: 'green-house-monitoring-4f6c7.appspot.com',
    iosBundleId: 'com.example.greenhouseMonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkiFyBP42CMk9DFLFZZ5QlRwa9ETqoJPs',
    appId: '1:1098012852802:ios:99153d969b17ebf4d023db',
    messagingSenderId: '1098012852802',
    projectId: 'green-house-monitoring-4f6c7',
    storageBucket: 'green-house-monitoring-4f6c7.appspot.com',
    iosBundleId: 'com.example.greenhouseMonitoring.RunnerTests',
  );
}
